name: var_dump
description: 'Dumps details in tree from variable. Optionally exits. Can use dump() or var_dump(), or dd() for "dump and die"'
version: 0.6.0
repository: https://github.com/insign/dart_var_dump
homepage: https://github.com/insign/dart_var_dump

environment:
  sdk: ^3.9.4

platforms:
  linux:
  macos:
  windows:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

dependencies:
  all_exit_codes: ^2.1.0
